# Лабораторная работа № 2

- Задание [ссылка на gh](https://github.com/catharsis96/numpy/blob/main/lab%202%20-%20NumPy.txt)
- Группа: Т12О-101М
- Студент: Томчик Никита

In [1]:
import numpy as np

#### Перемножить матрицы 5x3 и 3x2

In [2]:
np.dot(np.arange(15).reshape((5, 3)), np.arange(6).reshape((3, 2)))

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [3]:
arr = np.arange(11)
f = np.vectorize(lambda x: -x if x in range(3, 9) else x)
f(arr)

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

In [4]:
arr = np.arange(11)
arr[(arr >= 3) & (arr <= 8)] *= -1
arr

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

#### Создать 5x5 матрицу со значениями в строках от 0 до 4

In [5]:
np.array(list(range(5))*5).reshape((5, 5))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### Есть генератор, сделать с его помощью массив

In [6]:
def gen(n: int):
    for i in range(n):
        yield i

np.fromiter(gen(10), dtype=np.int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [7]:
np.linspace(0, 1, 11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### Отсортировать вектор

In [8]:
arr = np.arange(10, 0, -1)
arr.sort()
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Проверить, одинаковы ли 2 numpy массива

In [9]:
a = np.array([1, 2, 3])
b = np.array([3, 4, 5])

np.array_equal(a, b), np.array_equal(a, a)

(False, True)

#### Сделать массив неизменяемым

In [10]:
a = np.arange(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

#### Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную

In [11]:
coordinates = np.random.random((10, 2))

x, y = coordinates[:,0], coordinates[:,1]

radius = np.sqrt(x**2 + y**2)
angle = np.arctan2(y, x)

np.array([radius, angle])

array([[1.22446873, 0.67291885, 0.90171272, 0.21075431, 0.72639686,
        1.08306615, 0.9227207 , 1.16485379, 0.38245792, 0.9942485 ],
       [0.83742981, 1.56684616, 0.19467057, 1.44376562, 1.05595654,
        0.41389658, 1.3832278 , 0.6036563 , 1.20961873, 0.09365043]])

#### Заменить максимальный элемент на ноль

In [12]:
arr = np.arange(10)
arr[arr.argmax()] = 0
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 0])

#### Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [13]:
np.array(
    [(0, 0), (0, 1), (1, 0), (1, 1)],
    dtype=[('x', np.int), ('y', np.int)]
)

array([(0, 0), (0, 1), (1, 0), (1, 1)], dtype=[('x', '<i8'), ('y', '<i8')])

#### Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [14]:
x = np.arange(1, 10)
y = np.random.randint(20, 30, size=10)

C = 1 / (x.reshape((-1, 1)) - y)
C

array([[-0.03703704, -0.05263158, -0.03703704, -0.04761905, -0.04545455,
        -0.03703704, -0.04545455, -0.05263158, -0.05      , -0.03571429],
       [-0.03846154, -0.05555556, -0.03846154, -0.05      , -0.04761905,
        -0.03846154, -0.04761905, -0.05555556, -0.05263158, -0.03703704],
       [-0.04      , -0.05882353, -0.04      , -0.05263158, -0.05      ,
        -0.04      , -0.05      , -0.05882353, -0.05555556, -0.03846154],
       [-0.04166667, -0.0625    , -0.04166667, -0.05555556, -0.05263158,
        -0.04166667, -0.05263158, -0.0625    , -0.05882353, -0.04      ],
       [-0.04347826, -0.06666667, -0.04347826, -0.05882353, -0.05555556,
        -0.04347826, -0.05555556, -0.06666667, -0.0625    , -0.04166667],
       [-0.04545455, -0.07142857, -0.04545455, -0.0625    , -0.05882353,
        -0.04545455, -0.05882353, -0.07142857, -0.06666667, -0.04347826],
       [-0.04761905, -0.07692308, -0.04761905, -0.06666667, -0.0625    ,
        -0.04761905, -0.0625    , -0.07692308

#### Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [15]:
np_int_types = [
    np.uint, np.uint0, np.uint16, np.uint32, np.uint64, np.uint8, np.uintc, np.uintp,
    np.int, np.int0, np.int16, np.int32, np.int64, np.int8, np.intc, np.integer, np.intp,
]
np_float_types = [
    np.float, np.float128, np.float16, np.float32, np.float64,
]

for t in np_int_types:
    type_info = np.iinfo(t)
    print(t, type_info.min, type_info.max)

for t in np_float_types:
    type_info = np.finfo(t)
    print(t, type_info.min, type_info.max)


<class 'numpy.uint64'> 0 18446744073709551615
<class 'numpy.uint64'> 0 18446744073709551615
<class 'numpy.uint16'> 0 65535
<class 'numpy.uint32'> 0 4294967295
<class 'numpy.uint64'> 0 18446744073709551615
<class 'numpy.uint8'> 0 255
<class 'numpy.uint32'> 0 4294967295
<class 'numpy.uint64'> 0 18446744073709551615
<class 'int'> -9223372036854775808 9223372036854775807
<class 'numpy.int64'> -9223372036854775808 9223372036854775807
<class 'numpy.int16'> -32768 32767
<class 'numpy.int32'> -2147483648 2147483647
<class 'numpy.int64'> -9223372036854775808 9223372036854775807
<class 'numpy.int8'> -128 127
<class 'numpy.int32'> -2147483648 2147483647
<class 'numpy.integer'> -9223372036854775808 9223372036854775807
<class 'numpy.int64'> -9223372036854775808 9223372036854775807
<class 'float'> -1.7976931348623157e+308 1.7976931348623157e+308
<class 'numpy.float128'> -1.189731495357231765e+4932 1.189731495357231765e+4932
<class 'numpy.float16'> -65500.0 65500.0
<class 'numpy.float32'> -3.4028235e

#### Напечатать все значения в массиве

In [16]:
# а можно по русски опять, м?
arr = np.arange(10)
print(arr)

for i in arr:
    print(i, end=' ')
print()

[0 1 2 3 4 5 6 7 8 9]
0 1 2 3 4 5 6 7 8 9 


#### Найти ближайшее к заданному значению число в заданном массиве

In [17]:
arr = np.array([1, 2, 3, 6, 7, 8, 9, 10])

def find_nearest(array: np.ndarray, value):
    idx = (np.abs(array - value)).argmin()
    return array[idx]

find_nearest(arr, 4)

3

#### Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b)

In [18]:
np.zeros(10, dtype=[('x', np.int), ('y', np.int), ('color', np.uint, (3,))])

array([(0, 0, [0, 0, 0]), (0, 0, [0, 0, 0]), (0, 0, [0, 0, 0]),
       (0, 0, [0, 0, 0]), (0, 0, [0, 0, 0]), (0, 0, [0, 0, 0]),
       (0, 0, [0, 0, 0]), (0, 0, [0, 0, 0]), (0, 0, [0, 0, 0]),
       (0, 0, [0, 0, 0])],
      dtype=[('x', '<i8'), ('y', '<i8'), ('color', '<u8', (3,))])

#### Дан массив (100,2) координат, найти расстояние от каждой точки до каждой

In [19]:
coordinates = np.random.random((100, 2))

distances = np.zeros((100, 100))

for i in range(100):
    point_first = coordinates[i]
    for j in range(100):
        point_second = coordinates[j]

        distances[i][j] = np.linalg.norm(point_first - point_second)

distances

array([[0.        , 1.00417707, 1.05080138, ..., 0.71270475, 0.2382564 ,
        0.54626489],
       [1.00417707, 0.        , 0.25215918, ..., 0.35668193, 0.92755965,
        0.60733594],
       [1.05080138, 0.25215918, 0.        , ..., 0.33810016, 0.918982  ,
        0.55412429],
       ...,
       [0.71270475, 0.35668193, 0.33810016, ..., 0.        , 0.59129675,
        0.25078586],
       [0.2382564 , 0.92755965, 0.918982  , ..., 0.59129675, 0.        ,
        0.37133798],
       [0.54626489, 0.60733594, 0.55412429, ..., 0.25078586, 0.37133798,
        0.        ]])

#### Преобразовать массив из float в int

In [20]:
(np.random.random(size=10) + 5).astype(np.int)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Дан файл:
```csv
1,2,3,4,5
6,,,7,8
,,9,10,11
```
Как прочитать его?

In [21]:
with open('./test_file.txt', 'w') as f:
    f.write("1,2,3,4,5\n6,,,7,8\n,,9,10,11")

np.genfromtxt('./test_file.txt', delimiter=',')

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

#### Каков эквивалент функции enumerate для numpy массивов?

In [22]:
list(np.ndenumerate(np.arange(10)))

[((0,), 0),
 ((1,), 1),
 ((2,), 2),
 ((3,), 3),
 ((4,), 4),
 ((5,), 5),
 ((6,), 6),
 ((7,), 7),
 ((8,), 8),
 ((9,), 9)]

#### Сформировать 2D массив с распределением Гаусса

In [23]:
np.random.normal(size=(4, 4))

array([[ 0.90744299, -0.44503979, -0.36895866, -0.18898818],
       [ 0.65356732,  0.0727155 , -0.65700664, -0.50498812],
       [ 0.70063493, -1.04456024, -0.75727141,  1.21562394],
       [ 0.11650745, -0.89629879,  1.60076841, -0.47542853]])

#### Случайно расположить p элементов в 2D массив

In [24]:
p, m = 3, 5
x = [1] * p + [0] * (m * m - p)

np.random.shuffle(x)

np.mat(x).reshape(m, m)

matrix([[0, 0, 0, 0, 1],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0]])

#### Отнять среднее из каждой строки в матрице

In [25]:
matrix = np.arange(25).reshape(5, 5)
matrix - matrix.mean(axis=1, keepdims=True)

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

#### Отсортировать матрицу по n-ому столбцу

In [26]:
N = 3
matrix = np.arange(25).reshape(5, 5)[::-1]

matrix[matrix[:,N].argsort()]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### Определить, есть ли в 2D массиве нулевые столбцы

In [27]:
arr = np.random.randint(0,3,(3,10))
np.all((arr == 0), axis=1)

array([False, False, False])

#### Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [28]:
arr = np.ones(10)
print('array' ,arr)
indices = np.random.randint(0, len(arr), 20)
print('indices', indices)
arr += np.bincount(indices, minlength=len(arr))
arr

array [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
indices [5 6 4 6 3 1 7 6 1 2 8 2 9 9 5 7 1 8 7 5]


array([1., 4., 3., 2., 2., 4., 4., 4., 3., 3.])

#### Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [29]:
width, height = 16, 16

pixel_light = np.random.randint(0, 2, (height, width, 3)).astype(np.ubyte)

#        RED * 256^2                  GREEN * 256                BLUE
F = pixel_light[...,0] * 256 * 256 + pixel_light[...,1] * 256 + pixel_light[...,2]

np.unique(F)

array([  0,   1, 256, 257], dtype=uint16)

#### Дан четырехмерный массив, посчитать сумму по последним двум осям

In [30]:
arr = np.random.randint(0,10, (3,4,3,4))

arr.reshape(arr.shape[:-2] + (-1,)).sum(axis=-1)

array([[47, 51, 55, 56],
       [59, 50, 47, 47],
       [48, 56, 46, 34]])

#### Найти диагональные элементы произведения матриц

In [31]:
first = np.random.random((3, 5))
second = np.random.random((5, 3))

np.diag(np.dot(first, second))

array([0.66511517, 0.53126698, 0.36098474])