# Лабораторная работа № 3

- Задание [ссылка на gh](https://github.com/catharsis96/numpy/blob/main/lab%203%20-%20NumPy.txt)
- Группа: Т12О-101М
- Студент: Томчик Никита

In [1]:
import numpy as np

#### Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [2]:
arr = np.array([1,2,3,4,5])

arr_new = np.zeros(len(arr) + (len(arr)-1)*3)
arr_new[::3+1] = arr
arr_new

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### Поменять 2 строки в матрице

In [3]:
arr = np.arange(25).reshape(5,5)
print(arr)
arr[[0,1]] = arr[[1,0]]
arr

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти множество уникальных отрезков, составляющих все треугольники

In [4]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)

G

array([( 3,  3), ( 3, 62), ( 4, 46), ( 4, 63), ( 4, 69), ( 4, 87),
       ( 5, 13), ( 5, 99), ( 8, 50), ( 8, 58), (13, 76), (13, 92),
       (13, 99), (14, 48), (14, 99), (25, 60), (25, 95), (38, 52),
       (38, 79), (46, 63), (48, 99), (50, 58), (52, 79), (60, 95),
       (69, 87), (76, 92), (79, 89), (79, 95), (89, 95)],
      dtype=[('p0', '<i8'), ('p1', '<i8')])

#### Дан массив C; создать массив A, что np.bincount(A) == C

In [5]:
C = np.bincount([1,1,2,3,4,4,6])

np.repeat(np.arange(len(C)), C)

array([1, 1, 2, 3, 4, 4, 6])

#### Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]), каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1]))

In [6]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

rolling(np.arange(10), 3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

#### Инвертировать булево значение, или поменять знак у числового массива без создания нового

In [7]:
Z = np.random.randint(0,2,100)
np.logical_not(arr, out=arr)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [8]:
Z = np.random.uniform(-1.0,1.0,100)
np.negative(arr, out=arr)

array([[ 0,  0,  0,  0,  0],
       [-1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

#### Посчитать ранг матрицы

In [9]:
Z = np.random.uniform(0,1,(10,10))
np.linalg.matrix_rank(Z)

10

#### Найти наиболее частое значение в массиве

In [10]:
Z = np.random.randint(0,10,50)
np.bincount(Z).argmax()

3

#### Извлечь все смежные 3x3 блоки из 10x10 матрицы

In [11]:
from numpy.lib import stride_tricks

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0] - n)
j = 1 + (Z.shape[1] - n)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)

#### Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). Посчитать сумму p произведений матриц (результат имеет размерность (n,1))

In [12]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
S

array([[200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.]])

#### Дан массив 16x16, посчитать сумму по блокам 4x4

In [13]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(
    np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
    np.arange(0, Z.shape[1], k),
    axis=1,
)
S

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

#### Найти n наибольших значений в массиве

In [14]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print(Z[np.argpartition(-Z,n)[:n]])

[9999 9998 9997 9996 9995]


#### Построить прямое произведение массивов (все комбинации с каждым элементом)

In [15]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [16]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 1 2 3 4 5 6 7]


#### Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])

In [17]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[0 4 2]
 [4 3 1]
 [2 2 0]
 [2 2 3]
 [4 4 4]
 [1 2 1]
 [4 0 1]
 [1 0 3]
 [0 1 1]
 [2 4 4]]
[[0 4 2]
 [4 3 1]
 [2 2 0]
 [2 2 3]
 [1 2 1]
 [4 0 1]
 [1 0 3]
 [0 1 1]
 [2 4 4]]


#### Преобразовать вектор чисел в матрицу бинарных представлений

In [18]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### Дан двумерный массив. Найти все различные строки

In [19]:
Z = np.random.randint(0, 2, (6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 0]
 [1 0 1]]


#### Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul

In [20]:
# Useful docs for einsum -> http://ajcr.net/Basic-guide-to-einsum/

A = np.random.random((10,))
B = np.random.random((10,))

np.einsum('i->', A)       # np.sum(A)

5.47722895499831

In [21]:
np.einsum('i,i->i', A, B) # A * B

array([0.09934933, 0.18357544, 0.76659877, 0.65082897, 0.19603401,
       0.04251834, 0.17096352, 0.05387211, 0.07898155, 0.05259855])

In [22]:
np.einsum('i,i', A, B)    # np.inner(A, B)

2.2953205837807924

In [23]:
np.einsum('i,j', A, B)    # np.outer(A, B)

array([[0.09934933, 0.15098096, 0.18739527, 0.16583311, 0.07247749,
        0.01964713, 0.06227293, 0.01365029, 0.08621204, 0.19601633],
       [0.12079732, 0.18357544, 0.22785103, 0.20163393, 0.08812427,
        0.02388865, 0.0757167 , 0.01659718, 0.10482389, 0.23833325],
       [0.4064194 , 0.6176347 , 0.76659877, 0.67839204, 0.29649179,
        0.08037272, 0.25474685, 0.05584077, 0.35267721, 0.80186592],
       [0.38990658, 0.59254021, 0.73545186, 0.65082897, 0.28444533,
        0.07710718, 0.24439649, 0.05357196, 0.33834794, 0.76928611],
       [0.26871578, 0.40836681, 0.50685865, 0.44853826, 0.19603401,
        0.05314072, 0.16843315, 0.03692072, 0.2331826 , 0.53017654],
       [0.21500179, 0.32673778, 0.40554194, 0.35887929, 0.15684849,
        0.04251834, 0.1347648 , 0.02954058, 0.18657139, 0.42419878],
       [0.2727527 , 0.4145017 , 0.51447318, 0.45527664, 0.19897902,
        0.05393905, 0.17096352, 0.03747538, 0.2366857 , 0.53814137],
       [0.39209112, 0.59586005, 0.7395724