In [1]:
import numpy as np

Перемножить матрицы 5x3 и 3x2

In [43]:
np.dot(np.arange(15).reshape((5, 3)), np.arange(6).reshape((3, 2)))

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [42]:
arr = np.arange(11)
f = np.vectorize(lambda x: -x if x in range(3, 9) else x)
f(arr)

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

Создать 5x5 матрицу со значениями в строках от 0 до 4

In [12]:
np.array(list(range(5))*5).reshape((5, 5))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

Есть генератор, сделать с его помощью массив

In [17]:
def gen(n: int):
    for i in range(n):
        yield i

np.fromiter(gen(10), dtype=np.int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [25]:
np.linspace(0, 1, 11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

Отсортировать вектор

In [40]:
arr = np.arange(10, 0, -1)
arr.sort()
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Проверить, одинаковы ли 2 numpy массива

In [36]:
a = np.array([1, 2, 3])
b = np.array([3, 4, 5])

np.array_equal(a, b)

False

Сделать массив неизменяемым

In [37]:
a = np.arange(10)
a.flags.writeable = False

Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную

In [56]:
coordinates = np.random.random(20).reshape(10, 2)

x, y = coordinates[:,0], coordinates[:,1]

radius = np.sqrt(x**2 + y**2)
angle = np.arctan2(y, x)

np.array([radius, angle])

array([[1.19763947, 0.36826523, 0.87751505, 0.66248135, 0.80332421,
        1.20741708, 0.24936783, 0.63178482, 0.67101089, 0.97893844],
       [0.95189807, 1.28330593, 1.49110398, 1.22829674, 1.33300706,
        0.66080981, 1.01898868, 0.72482107, 1.51902713, 0.16351017]])

Заменить максимальный элемент на ноль

In [59]:
arr = np.arange(10)
arr[arr.argmax()] = 0
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 0])

Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [80]:
np.array(
    [(0, 0), (0, 1), (1, 0), (1, 1)],
    dtype=[('x', np.int), ('y', np.int)]
)

array([(0, 0), (0, 1), (1, 0), (1, 1)], dtype=[('x', '<i8'), ('y', '<i8')])

Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [71]:
x = np.arange(1, 10)
y = np.random.randint(20, 30, size=10)

C = 1 / (x.reshape((-1, 1)) - y)
C

array([[-0.04      , -0.04      , -0.03846154, -0.05      , -0.03846154,
        -0.03846154, -0.04761905, -0.05      , -0.05263158, -0.05      ],
       [-0.04166667, -0.04166667, -0.04      , -0.05263158, -0.04      ,
        -0.04      , -0.05      , -0.05263158, -0.05555556, -0.05263158],
       [-0.04347826, -0.04347826, -0.04166667, -0.05555556, -0.04166667,
        -0.04166667, -0.05263158, -0.05555556, -0.05882353, -0.05555556],
       [-0.04545455, -0.04545455, -0.04347826, -0.05882353, -0.04347826,
        -0.04347826, -0.05555556, -0.05882353, -0.0625    , -0.05882353],
       [-0.04761905, -0.04761905, -0.04545455, -0.0625    , -0.04545455,
        -0.04545455, -0.05882353, -0.0625    , -0.06666667, -0.0625    ],
       [-0.05      , -0.05      , -0.04761905, -0.06666667, -0.04761905,
        -0.04761905, -0.0625    , -0.06666667, -0.07142857, -0.06666667],
       [-0.05263158, -0.05263158, -0.05      , -0.07142857, -0.05      ,
        -0.05      , -0.06666667, -0.07142857

Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [77]:
np_int_types = [
    np.uint, np.uint0, np.uint16, np.uint32, np.uint64, np.uint8, np.uintc, np.uintp,
    np.int, np.int0, np.int16, np.int32, np.int64, np.int8, np.intc, np.integer, np.intp,
]
np_float_types = [
    np.float, np.float128, np.float16, np.float32, np.float64,
]

for t in np_int_types:
    type_info = np.iinfo(t)
    print(t, type_info.min, type_info.max)

for t in np_float_types:
    type_info = np.finfo(t)
    print(t, type_info.min, type_info.max)


<class 'numpy.uint64'> 0 18446744073709551615
<class 'numpy.uint64'> 0 18446744073709551615
<class 'numpy.uint16'> 0 65535
<class 'numpy.uint32'> 0 4294967295
<class 'numpy.uint64'> 0 18446744073709551615
<class 'numpy.uint8'> 0 255
<class 'numpy.uint32'> 0 4294967295
<class 'numpy.uint64'> 0 18446744073709551615
<class 'int'> -9223372036854775808 9223372036854775807
<class 'numpy.int64'> -9223372036854775808 9223372036854775807
<class 'numpy.int16'> -32768 32767
<class 'numpy.int32'> -2147483648 2147483647
<class 'numpy.int64'> -9223372036854775808 9223372036854775807
<class 'numpy.int8'> -128 127
<class 'numpy.int32'> -2147483648 2147483647
<class 'numpy.integer'> -9223372036854775808 9223372036854775807
<class 'numpy.int64'> -9223372036854775808 9223372036854775807
<class 'float'> -1.7976931348623157e+308 1.7976931348623157e+308
<class 'numpy.float128'> -1.189731495357231765e+4932 1.189731495357231765e+4932
<class 'numpy.float16'> -65500.0 65500.0
<class 'numpy.float32'> -3.4028235e

Напечатать все значения в массиве

In [78]:
# а можно по русски опять, м?
arr = np.arange(10)
print(arr)

for i in arr:
    print(i, end=' ')
print()

[0 1 2 3 4 5 6 7 8 9]
0 1 2 3 4 5 6 7 8 9 


Найти ближайшее к заданному значению число в заданном массиве

In [79]:
arr = np.array([1, 2, 3, 6, 7, 8, 9, 10])

def find_nearest(array: np.ndarray, value):
    idx = (np.abs(array - value)).argmin()
    return array[idx]

find_nearest(arr, 4)

3

Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b)

In [84]:
np.array(
    [(0, 0, (255, 255, 255)), (0, 1, (255, 120, 110)), (1, 0, (123, 200, 11)), (1, 1, (0, 17, 44))],
    dtype=[('x', np.int), ('y', np.int), ('color', np.uint, (3,))]
)

array([(0, 0, [255, 255, 255]), (0, 1, [255, 120, 110]),
       (1, 0, [123, 200,  11]), (1, 1, [  0,  17,  44])],
      dtype=[('x', '<i8'), ('y', '<i8'), ('color', '<u8', (3,))])

Дан массив (100,2) координат, найти расстояние от каждой точки до каждой

In [90]:
# лень делать сейчас

Преобразовать массив из float в int

In [96]:
(np.random.random(size=10) + 5).astype(np.int)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

Дан файл:
```
1,2,3,4,5
6,,,7,8
,,9,10,11
```
Как прочитать его?

In [100]:
with open('./test_file.txt', 'w') as f:
    f.write("1,2,3,4,5\n6,,,7,8\n,,9,10,11")

np.genfromtxt('./test_file.txt', delimiter=',')

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

Каков эквивалент функции enumerate для numpy массивов?

In [102]:
list(np.ndenumerate(np.arange(10)))

[((0,), 0),
 ((1,), 1),
 ((2,), 2),
 ((3,), 3),
 ((4,), 4),
 ((5,), 5),
 ((6,), 6),
 ((7,), 7),
 ((8,), 8),
 ((9,), 9)]

Сформировать 2D массив с распределением Гаусса

In [105]:
np.random.normal(size=(4, 4))

array([[-0.16052103, -0.85261017, -0.87102457, -1.29409983],
       [-0.51220519, -1.38023763, -0.79742953,  0.18188826],
       [ 0.13749309,  0.57317851, -0.29818341, -1.21041555],
       [ 0.20294658,  1.10315957, -0.53718745,  0.35111561]])

Случайно расположить p элементов в 2D массив

In [109]:
p, m = 3, 5
x = [True] * p + [False] * (m * m - p)

np.random.shuffle(x)

np.mat(x).reshape(m, m)

matrix([[False, False,  True, False, False],
        [False, False, False, False,  True],
        [False, False, False, False, False],
        [False, False, False, False,  True],
        [False, False, False, False, False]])

Отнять среднее из каждой строки в матрице

In [138]:
matrix = np.arange(25).reshape(5, 5)
matrix - matrix.mean(axis=1, keepdims=True)

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

Отсортировать матрицу по n-ому столбцу

In [143]:
N = 3
matrix = np.arange(25).reshape(5, 5)[::-1]

matrix[matrix[:,N].argsort()]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

Определить, есть ли в 2D массиве нулевые столбцы

In [144]:
# потом доделаю

Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [145]:
# потом доделаю

Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [146]:
# потом доделаю

Дан четырехмерный массив, посчитать сумму по последним двум осям

In [147]:
# потом доделаю

Найти диагональные элементы произведения матриц

In [148]:
# потом доделаю